// Interface automatically generated by schemas-to-ts

export interface PageInfomation {
  title: string;
  description?: string;
  slug: string;
  seoImage?: any;
}
export interface PageInfomation_Plain {
  title: string;
  description?: string;
  slug: string;
  seoImage?: any;
}

export interface PageInfomation_NoRelations {
  title: string;
  description?: string;
  slug: string;
  seoImage?: number;
}
